# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCommServer', '0004_auto_20160908_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycommdevice',
            name='createdDate',
            field=models.DateTimeField(verbose_name='2016-09-08 12:49:07'),
        ),
        migrations.AlterField(
            model_name='mycommmsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2016-09-08 12:49:07'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2016-09-08 12:49:07'),
        ),
    ]
